# 기본 설정은 local 프로필로 작동합니다.
spring.profiles.active: local

##### 공통 설정 #####
server:
  servlet:
    session:
      timeout: 600
      tracking-modes: cookie
    encoding:
      charset: UTF-8
      force: true
    # ResponseStatusException message
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  security:
    user:
      name: minskim2
      roles: USER, ADMIN
    oauth2:
      client:
        registration:
          new_match42:
            client-id: ${OAUTH_UID}
            client-secret: ${OAUTH_SECRET}
            scope:
              - public
              - projects
              - profile
              - elearning
              - tig
              - forum
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

        provider:
          new_match42:
            authorization-uri: https://api.intra.42.fr/oauth/authorize
            token-uri: https://api.intra.42.fr/oauth/token
            user-info-uri: https://api.intra.42.fr/v2/me
            user-name-attribute: login

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    # this option is dangerous
    hibernate.ddl-auto: create-drop

OAuth:
  uid: ${OAUTH_UID}
  secret: ${OAUTH_SECRET}




---

##### 개발할 때 사용하는 local 환경 설정 프로필 #####
spring.config.activate.on-profile: local

server:
  ip: localhost
  port: 80

spring:
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/NEW_MATCH42?characterEncoding=UTF-8&serverTimezone=UTC
  security:
    user:
      password: 1234

jwt:
  secret: "mySecretmySecretmySecretmySecretmySecretmySecretmySecret"


---

##### 실제 NCP 서버용 환경 설정 프로필 #####
spring.config.activate.on-profile: prod

server:
  ip: ${NCP_IP} # 115.85.181.92
  port: ${SPRING_PORT}  # 80

spring:
  datasource:
    password: ${MYSQL_ROOT_PASSWORD} # 1234
    url: jdbc:mysql://${DB_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&serverTimezone=UTC
  security:
    user:
      password: ${SPRING_SECURITY_PASSWORD} # 1234

jwt:
  secret: ${JWT_SECRET}


---

#  ssl:
#    enabled: true
#    key-store: src/main/resources/bootsecurity.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: bootsecurity
