# 기본 설정은 local
spring.profile.active: local

# 공통 데이터
server:
  servlet:
    session:
      timeout: 600
      tracking-modes: cookie
    # ResponseStatusException message
    error:
      include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

jpa:
  open-in-view: false
  generate-ddl: true
  show-sql: true
  defer-datasource-initialization: true
  # this option is dangerous
  hibernate.ddl-auto: create-drop

# Spring Security
security:
  user:
    name: minskim2
    roles: USER, ADMIN

---
# local 환경 설정
spring.config.activate.on-profile: local

server:
  ip: localhost
  port: 80

spring:
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/NEW_MATCH42?characterEncoding=UTF-8&serverTimezone=UTC
  security:
    user:
      password: 1234
---
# prod 환경 설정
spring.config.activate.on-profile: prod

server:
  ip: ${NCP_IP} # 115.85.181.92
  port: ${SPRING_PORT}  # 80

spring:
  datasource:
    password: ${MYSQL_ROOT_PASSWORD} # 1234
    url: jdbc:mysql://${DB_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&serverTimezone=UTC
  security:
    user:
      password: ${SPRING_SECURITY_PASSWORD} # 1234

---

#  ssl:
#    enabled: true
#    key-store: src/main/resources/bootsecurity.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: bootsecurity
