# server
server:
  port: 80
  servlet:
    session:
      timeout: 600
      tracking-modes: cookie
  # ResponseStatusException message
  error:
    include-message: always
  # ssl ??? ??
#  ssl:
#    enabled: true
#    key-store: src/main/resources/bootsecurity.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: bootsecurity

# spring
spring:
  # MYSQL
  datasource.driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/NEW_MATCH42?characterEncoding=UTF-8&serverTimezone=UTC

  # jpa
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  # this option is dangerous
    hibernate.ddl-auto: create-drop

  # Spring Security
  security:
    user:
      name: minskim2
      password: 1234
      roles: USER, ADMIN